name: Test

on:
  pull_request:
  push:

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.12"]
        include:
        - os: "macos-14"
          target-platform: arm-64
        - os: "macos-13"
          target-platform: osx-64
        - os: "ubuntu-22.04"
          target-platform: linux-64
        - os: "windows-2022"
          target-platform: win-64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"
      - name: Test
        run: |
          mkdir build
          cd build
          cmake -S .. -G Ninja
          ninja test
