name: Test

on:
  pull_request:
  push:

jobs:
  build:
    name: ${{ matrix.platform.os }} / ${{ matrix.platform.arch }} / python-${{ matrix.python_version }}
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # min version, max version
        # 3.11 is the first version supported by darwin / arm64 runner
        python_version: ["3.11", "3.12"]
        platform:
          - { os: "macos-14", arch: arm64 }
          - { os: "macos-13", arch: x64 }
          - { os: "ubuntu-22.04", arch: x64 }
          - { os: "windows-2022", arch: x64 }
    steps:
      - name: Setup Linux platform
        if: ${{ startsWith(matrix.platform.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install libegl1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        id: py
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - name: Install packages
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          $py_interpreter -m pip install \
            -r environment/configuration/requirements.txt \
            -r environment/configuration/requirements-dev.txt
      - name: Run tests
        run: |
          mkdir build
          cd build
          cmake -S .. -G Ninja
          ctest --test-dir . --output-on-failure
      - name: Create documentation
        run: |
          cmake --build build --target documentation
      - name: Create and verify release
        run: |
          py_interpreter="${{ steps.py.outputs.python-path }}"
          PYTHONPATH=source/package ${py_interpreter} environment/script/create_and_verify_release.py ./build
          cmake --build build --target installer_release
